name: CI/CD Pipeline

on:
  push:
    branches:
      - feature/full-setup
  pull_request:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install frontend dependencies
        run: |
          cd frontend
          npm install
          npm run build

      - name: Install backend dependencies
        run: |
          cd backend
          npm install

      - name: Deploy to Render
        uses: render-examples/deploy-render-action@v1
        with:
          apiKey: ${{ secrets.RENDER_API_KEY }}
